### ISSUE TITLE
Ubuntu22.04 LTS npm 安装、Appimage运行、Snap安装报错

### ISSUE THREAD

**Issue by fgwsz** [mycard/mycard#17]
# npm install
npm ERR! Cannot read property 'insert' of undefined
# Appimage运行
A JavaScript error occurred in the main process
Uncaught Exception:
undefined: undefined
# snap install
error: cannot find signatures with metadata for snap "mycard_3.0.36_amd64.snap"
# snap intall --dangerous:
## mycard
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
A JavaScript error occurred in the main process
Uncaught Exception:
undefined: undefined
shm_open() failed: Permission denied
## sudo mycard
mkdir: cannot create directory '/run/user/0': Permission denied
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Documents': 
No such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Desktop': No
 such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Downloads': 
No such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Music': No s
uch file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Pictures': N
o such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Videos': No 
such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Public': No 
such file or directory
ln: failed to create symbolic link '/root/snap/mycard/x4/snap/mycard/x4/Templates': 
No such file or directory
Authorization required, but no authorization protocol specified

**Comment by purerosefallen** [comment]
We develop on https://code.mycard.moe/mycard/mycard
It works on Ubuntu 22.04, however Node.js version 16.14 is required.
